### ISSUE TITLE
Does not play nicely with ItemJoin

### ISSUE THREAD

**Issue by SlimeDog** [Ruinscraft/Panilla#1]
Spigot 1.13.2 latest
ItemJoin 5.0.4-b225
DeluxeMenus 1.10.5
Panilla 1.0

Panilla/config.yml
```
# Panilla configuration

# Do not change
configuration-version: 1.0

locale-file: en_US.yml

# Logging options
logging:
  console: false
  chat: false

# Strictness of how much you wish to enforce
#   lenient - Only prevent game-breaking things or crashes
#   average - Prevent most abusive things
#   strict  - Prevent anything non-vanilla
strictness: average

# Whitelist NBT tags from being checked
nbt-whitelist:
#  - Enchantments   # 1.13 format
#  - ench           # 1.12 format
```
I have configured ItemJoin with a clock in slot 8, which when right-clicked should open a DM menu. With Panilla enabled, right-click on the clock is ignored. Please advise.
